path: /Users/toby/OneDrive/Documents/Github/Boats-Image-Recognition/data
train: images
val: images

names:
  0: boat
  1: boat number
  2: Optimist
  3: Topper
  4: Laser
  5: Tera
  6: Feva
  7: 29er
  8: RS Double handers
  9: Aero
  10: Europe
  11: 400s
  12: Solo